### ISSUE TITLE
When open the program, it displays error...

### ISSUE THREAD

**Issue by elvarr** [feodoran/harbour-mercury#3]
Hello, chstem! When open the program, it displays this error:

> 2017-09-21 19:16:18,995 INFO: Python: Mercury Version: 0.1 
> 2017-09-21 19:16:18,996 INFO: Python: Telethon Client Version: 0.13.4 
> 2017-09-21 19:16:18,996 INFO: Python: Connecting to Telegram servers ... 
> 2017-09-21 19:16:19,315 ERROR: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "/usr/share/harbour-mercury/TgClient/__init__.py", line 67, in connect
>     if not client.client.connect():
> 
>   File "/usr/lib/python3.4/site-packages/telethon/telegram_client.py", line 150, in connect
>     ok = super().connect(exported_auth=exported_auth)
> 
>   File "/usr/lib/python3.4/site-packages/telethon/telegram_bare_client.py", line 121, in connect
>     authenticator.do_authentication(connection)
> 
>   File "/usr/lib/python3.4/site-packages/telethon/network/authenticator.py", line 20, in do_authentication
>     return _do_authentication(connection)
> 
>   File "/usr/lib/python3.4/site-packages/telethon/network/authenticator.py", line 40, in _do_authentication
>     sender.send(writer.get_bytes())
> 
>   File "/usr/lib/python3.4/site-packages/telethon/network/mtproto_plain_sender.py", line 35, in send
>     self._connection.send(packet)
> 
>   File "/usr/lib/python3.4/site-packages/telethon/network/connection.py", line 161, in send
>     raise ValueError('Invalid connection mode specified: ' + str(self._mode))
> 
> ValueError: Invalid connection mode specified: None

 
Through the terminal (python3), everything is fine.

**Comment by chstem** [comment]
This is probably an issue with the Telethon Version. I had no time to test 0.13 yet. Can you try 0.12?

`pip3 install telethon==0.12`

**Comment by elvarr** [comment]
Thank you! Managed to login. Another problem when I choose "Show Contacts":

> 2017-09-23 11:03:33,458 INFO: Python: Mercury Version: 0.1 
> 2017-09-23 11:03:33,458 INFO: Python: Telethon Client Version: 0.12 
> 2017-09-23 11:03:33,459 INFO: Python: Connecting to Telegram servers ... 
> 2017-09-23 11:03:34,594 INFO: Python: requesting updates, last state: 4581, 1506146462.0 
> 2017-09-23 11:03:50,150 ERROR: Return value of PyObject call is NULL: Traceback (most recent call last):
> 
>   File "/usr/share/harbour-mercury/TgClient/__init__.py", line 90, in call
>     getattr(client, method)(*args)
> 
>   File "/usr/share/harbour-mercury/TgClient/Client.py", line 112, in request_contacts
>     self.get_contacts()
> 
>   File "/usr/share/harbour-mercury/TgClient/Client.py", line 413, in get_contacts
>     r = self.invoke(tl.functions.contacts.GetContactsRequest(self.api_hash))
> 
> AttributeError: 'Client' object has no attribute 'api_hash'

**Comment by chstem** [comment]
I fixed the contacts issue in 58d8abb. The other one I can reproduce, but did not solve yet.

**Comment by elvarr** [comment]
Thanks It works.

**Comment by chstem** [comment]
This and some other issues coming with recent Telethon updates are now fixed, therefor I close here.

Note: Telethon 0.14.2 has some issues which are already fixed, but currently only available on github.
