### ISSUE TITLE
Switch to tdlib-python!

### ISSUE THREAD

**Issue by paolomi** [feodoran/harbour-mercury#4]
TDLib is an official, cross-platform, fully functional Telegram client, made by official Telegram developers. There is also a python wrapper. What do you think of switching to tdlib-python?
https://github.com/JunaidBabu/tdlib-python

Actual performance issues should disappear too. What is your opinion?

**Comment by chstem** [comment]
I very briefly played around with TDLib. It might be an option, but with [depecher](https://github.com/blacksailer/depecher) we have something much more promissing now. 

Mercury might still be interesting as an alternative Python-based approach, which would then fit better with Telethon. But as long as Telethon does not reach some stable version it is hard to predict which API will have the more appealing features.

**Comment by paolomi** [comment]
Thanks for your reply :-)

Then let's hope that depecher developes quickly or that Telethon switches to TDLib :smile: or both :smile: 

I close this issue. Bye :)
